const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];const rnd=a=>a[Math.floor(Math.random()*a.length)];const ri=(a,b)=>Math.floor(Math.random()*(b-a+1))+a;const clamp=(n,a=0,b=100)=>Math.max(a,Math.min(b,n));

const BASE=()=>({
  version:2,started:false,ended:false,playerRole:"mother",childName:"ひなた",phase:"pregnancy",pregnancyWeek:8,age:-1,actionCount:0,
  seed:{congenital:ri(0,100),premature:ri(0,100),baselineHealth:ri(48,94),temperament:ri(0,100)},
  stats:{money:55,cleanliness:55,family:58,partnerTrust:58,homeStress:18,prenatalRisk:8,prenatalCare:30,health:0,kindness:0,independence:0,attachment:0,dependence:0,rebellion:0,sociability:0,selfEsteem:0,school:0,delinquency:0},
  flags:{premature:false,nicu:false,chronic:false,severeMedical:false,parentsSeparated:false,partnerGone:false},
  appearance:{expression:"neutral",injury:"none",condition:"none",tempActions:0},history:[],discovered:[],usedEvents:[],settings:{bgm:true,se:true,voice:true}
});
let state=BASE(),manifest=null,events=[],diary=null,dialogueQueue=[],afterDialogue=null;

const ACTIONS_CHILD=[["talk","話す","今日あったことや気持ちを聞く"],["play","一緒に遊ぶ","家や外で遊ぶ"],["outside","外出する","散歩・公園・買い物など"],["learn","生活・勉強","年齢に合ったことを教える"],["rest","休む","家で静かに過ごす"],["medical","病院・体調","気になる体調を確認する"]];
const ACTIONS_PREG_MOTHER=[["rest","休む","身体を休める"],["checkup","健診・病院","妊娠中の身体を確認する"],["home","家のこと","掃除や育児準備をする"],["partner","夫と話す","二人で過ごす"],["free","好きに過ごす","その時したいことを選ぶ"],["work","仕事・外出","働く、買い物へ行く"]];
const ACTIONS_PREG_FATHER=[["partner","妻と話す","体調やこれからのことを話す"],["home","家のこと","家事や育児準備をする"],["work","仕事","家計のために働く"],["free","自分の時間","自由に過ごす"],["checkup","健診に関わる","付き添いや結果を聞く"],["rest","休む","家で過ごす"]];

async function loadData(){manifest=await fetch("./data/events/index.json").then(r=>r.json());diary=await fetch("./data/diary/fragments.json").then(r=>r.json());const packs=await Promise.all(manifest.files.map(p=>fetch(p).then(r=>{if(!r.ok)throw new Error(p);return r.json()})));events=packs.flatMap(x=>Array.isArray(x)?x:[x]);}
function init(){
  $$(".role").forEach(b=>b.onclick=()=>{gameAudio.click();vibrate(10);$$(".role").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");state.playerRole=b.dataset.role});
  $("#startBtn").onclick=startGame;$("#loadBtn").onclick=showSaves;$("#recordsBtn").onclick=showRecords;$("#saveBtn").onclick=showSaves;$("#settingsBtn").onclick=showSettings;$("#closeModal").onclick=closeModal;$("#modalBackdrop").onclick=e=>{if(e.target.id==="modalBackdrop")closeModal()};$("#speakerBubble").onclick=nextDialogue;$("#ageUpBtn").onclick=confirmAgeUp;$("#diaryBtn").onclick=showDiary;$("#endingRecordsBtn").onclick=showRecords;$("#restartBtn").onclick=()=>location.reload();render();
}
async function startGame(){await gameAudio.unlock();state=BASE();state.started=true;state.playerRole=$(".role.selected")?.dataset.role||"mother";state.childName=$("#nameInput").value.trim()||"ひなた";addHistory("妊娠8週","この家族の記録が始まった。","start");$("#setupScreen").classList.add("hidden");$("#playScreen").classList.remove("hidden");gameAudio.startBGM("pregnancy");render();startPregnancyOpening();}
function startPregnancyOpening(){const lines=state.playerRole==="mother"?[{speaker:"mother",expression:"neutral",text:"……まだ、あんまり実感ないな。"},{speaker:"father",expression:"happy",text:"でも、これから少しずつ変わってくんだろ。"},{speaker:"mother",expression:"happy",text:"うん。ちゃんと育ってくれるといいね。"}]:[{speaker:"father",expression:"neutral",text:"本当に、俺が父親になるのか。"},{speaker:"mother",expression:"happy",text:"何その顔。今さら？"},{speaker:"father",expression:"happy",text:"いや……ちょっとだけ緊張してる。"}];runDialogue(lines,showActions);}

function showActions(){dialogueQueue=[];afterDialogue=null;$("#speakerBubble").classList.add("hidden");const arr=state.phase==="pregnancy"?(state.playerRole==="mother"?ACTIONS_PREG_MOTHER:ACTIONS_PREG_FATHER):ACTIONS_CHILD;$("#actionButtons").innerHTML="";arr.forEach(([id,label,hint])=>{const b=document.createElement("button");b.className="action";b.innerHTML=`<strong>${esc(label)}</strong><span>${esc(hint)}</span>`;b.onclick=()=>performAction(id);$("#actionButtons").appendChild(b)});$("#actionTitle").textContent=state.phase==="pregnancy"?"次にどう過ごす？":`${state.childName}と何をする？`;$("#actionLead").textContent=state.phase==="pregnancy"?`現在、妊娠${state.pregnancyWeek}週。選ぶたびに少しずつ時間が進みます。`:`${state.age}歳のまま、好きなだけ行動できます。年齢を上げたい時だけ「次の年齢へ」を押してください。`;$("#ageUpBtn").classList.toggle("hidden",state.phase!=="child");render();}

function performAction(category){gameAudio.click();vibrate(14);tickTemporaryAppearance();const candidates=events.filter(e=>{if(e.phase!==state.phase)return false;if(e.category&&e.category!==category)return false;if(e.roles&&!e.roles.includes(state.playerRole))return false;if(e.minWeek!=null&&state.pregnancyWeek<e.minWeek)return false;if(e.maxWeek!=null&&state.pregnancyWeek>e.maxWeek)return false;if(e.minAge!=null&&state.age<e.minAge)return false;if(e.maxAge!=null&&state.age>e.maxAge)return false;if(e.conditions&&!conditionsPass(e.conditions))return false;return true});const pool=[];candidates.forEach(e=>{for(let i=0;i<(e.weight||1);i++)pool.push(e)});if(!pool.length){state.phase==="pregnancy"?genericPregnancyAction(category):genericChildAction(category);return}launchEvent(rnd(pool));}
function launchEvent(ev){state.usedEvents.push(ev.id);runDialogue(resolveDialogue(ev.intro||[]),()=>showChoices(ev));}
function showChoices(ev){$("#speakerBubble").classList.add("hidden");$("#actionButtons").innerHTML="";$("#actionTitle").textContent=fill(ev.title||"どうする？");$("#actionLead").textContent=fill(pickText(ev.prompt||""));(ev.choices||[]).filter(c=>!c.conditions||conditionsPass(c.conditions)).forEach(c=>{const b=document.createElement("button");b.className="action";b.innerHTML=`<strong>${esc(fill(c.label))}</strong><span>${esc(fill(pickText(c.hint||"")))}</span>`;b.onclick=()=>choose(ev,c);$("#actionButtons").appendChild(b)});}
function choose(ev,c){gameAudio.confirm();vibrate(18);applyEffects(c.effects||{});if(c.flags)Object.assign(state.flags,c.flags);if(c.appearance)applyAppearance(c.appearance);if(c.discover)discover(c.discover);const record=fill(pickText(c.record||c.label));const label=state.phase==="pregnancy"?`妊娠${state.pregnancyWeek}週`:`${state.age}歳`;addHistory(label,record,ev.id);$("#eventLog").textContent=record;if(state.phase==="pregnancy")state.pregnancyWeek+=c.advanceWeeks||ev.advanceWeeks||ri(2,4);else state.actionCount++;runDialogue(resolveDialogue(c.result||[]),()=>{if(state.phase==="pregnancy"&&shouldBirth())doBirth();else showActions()});}

function genericPregnancyAction(category){
  const role=state.playerRole,partner=role==="mother"?"father":"mother";
  const map={
    rest:{rec:"家で静かに休んだ。",eff:{homeStress:-2,prenatalCare:1},lines:[{speaker:"player",expression:"sleepy",text:["今日はちょっと休もう。","少し横になろうかな。"]},{speaker:partner,expression:"happy",text:["うん、休んで。","今日はゆっくりしよう。"]}]},
    checkup:{rec:"妊娠中の体調について確認した。",eff:{prenatalCare:3,money:-1},lines:[{speaker:"partner",expression:"neutral",text:["何か変わったことあった？","先生、何て言ってた？"]},{speaker:"player",expression:"neutral",text:["今のところ大丈夫。","ちゃんと確認してきたよ。"]}]},
    home:{rec:"家を整え、赤ちゃんを迎える準備をした。",eff:{cleanliness:5,family:2,money:-1},lines:[{speaker:"player",expression:"happy",text:["ここ、もう少し片づけよう。","この辺に赤ちゃんの物置けそう。"]},{speaker:partner,expression:"happy",text:"ちょっとずつ家っぽくなってきたな。"}]},
    partner:{rec:"夫婦でこれからのことを話した。",eff:{partnerTrust:3,family:2},lines:[{speaker:"player",expression:"neutral",text:["生まれたらどうなるかな。","ちゃんとやっていけるかな。"]},{speaker:partner,expression:"happy",text:["二人で考えてこう。","まあ、なんとかなるって。"]}]},
    free:{rec:"自分の時間を過ごした。",eff:{homeStress:-1},lines:[{speaker:"player",expression:"happy",text:["ちょっと好きなことしよ。","今のうちにのんびりしよう。"]}]},
    work:{rec:"仕事や外出をして過ごした。",eff:{money:4,homeStress:1},lines:[{speaker:"player",expression:"neutral",text:["行ってきます。","今日はちょっと忙しいな。"]},{speaker:partner,expression:"happy",text:"無理しすぎないでね。"}]}
  };
  const d=map[category]||map.rest;applyEffects(d.eff);const label=`妊娠${state.pregnancyWeek}週`;addHistory(label,d.rec,"generic_preg");$("#eventLog").textContent=d.rec;state.pregnancyWeek+=ri(2,3);runDialogue(resolveDialogue(d.lines),()=>{if(shouldBirth())doBirth();else showActions()});
}
function genericChildAction(category){
  const generic={talk:[{speaker:"child",expression:"happy",text:["ねえ、今日ね。","ちょっと聞いてほしいことある。","あのね、話していい？"]},{speaker:"player",expression:"neutral",text:["うん、聞いてるよ。","どうした？","なにがあったの？"]}],play:[{speaker:"child",expression:"happy",text:["いっしょにやろ！","もう一回！","これ、見てて！"]}],outside:[{speaker:"child",expression:"happy",text:["外いくの？","今日はどこ行く？","はやく行こ！"]}],learn:[{speaker:"child",expression:"neutral",text:["これ、どうやるの？","むずかしい……。","わかんない。"]}],rest:[{speaker:"child",expression:"sleepy",text:["ちょっとねむい……。","今日はのんびりしたい。","ここにいていい？"]}],medical:[{speaker:"child",expression:state.flags.chronic?"sick":"neutral",text:state.flags.chronic?["また病院？","今日も診てもらうの？"]:["どこか悪いの？","病院いくの？"]}]};
  const lines=generic[category]||[{speaker:"child",expression:"neutral",text:"今日は何する？"}];const eff=category==="talk"?{attachment:2,kindness:1}:category==="play"?{sociability:2,attachment:1}:category==="learn"?{independence:1,school:2}:category==="rest"?{homeStress:-2}:category==="medical"?{health:1,money:-1}:{independence:1};applyEffects(eff);state.actionCount++;const rec=`${state.childName}と${({talk:"話をした",play:"一緒に遊んだ",outside:"外出した",learn:"生活や勉強を見た",rest:"家で休んだ",medical:"体調を確認した"})[category]||"時間を過ごした"}。`;addHistory(`${state.age}歳`,rec,"generic");$("#eventLog").textContent=rec;runDialogue(resolveDialogue(lines),showActions);
}

function runDialogue(lines,done){dialogueQueue=lines.slice();afterDialogue=done;nextDialogue();}
function nextDialogue(){if(!dialogueQueue.length){$("#speakerBubble").classList.add("hidden");const fn=afterDialogue;afterDialogue=null;if(fn)fn();return}gameAudio.click();const l=dialogueQueue.shift(),speaker=l.speaker||"child",text=fill(pickText(l.text||""));setExpression(speaker,l.expression||"neutral");$("#speakerName").textContent=speakerName(speaker);$("#speakerText").textContent=text;$("#speakerBubble").classList.remove("hidden");gameAudio.speak(text,speaker==="player"?state.playerRole:speaker==="partner"?(state.playerRole==="mother"?"father":"mother"):speaker);}
function resolveDialogue(lines){return lines.map(x=>({...x,text:pickText(x.text)}));}
function speakerName(s){if(s==="child")return state.childName;if(s==="mother")return"母";if(s==="father")return"父";if(s==="player")return state.playerRole==="mother"?"母":"父";if(s==="partner")return state.playerRole==="mother"?"父":"母";return s;}
function setExpression(speaker,exp){["fatherSprite","motherSprite","childSprite"].forEach(id=>{const el=$("#"+id);[...el.classList].filter(x=>x.startsWith("expression-")).forEach(x=>el.classList.remove(x))});const real=speaker==="player"?state.playerRole:speaker==="partner"?(state.playerRole==="mother"?"father":"mother"):speaker;const el=real==="father"?$("#fatherSprite"):real==="mother"?$("#motherSprite"):$("#childSprite");if(el)el.classList.add("expression-"+exp);if(real==="child")state.appearance.expression=exp;}
function applyAppearance(a){if(a.expression)state.appearance.expression=a.expression;if(a.injury)state.appearance.injury=a.injury;if(a.condition)state.appearance.condition=a.condition;if(a.duration)state.appearance.tempActions=a.duration;}
function tickTemporaryAppearance(){if(state.appearance.tempActions>0){state.appearance.tempActions--;if(state.appearance.tempActions<=0){state.appearance.injury="none";if(!state.flags.chronic&&!state.flags.severeMedical)state.appearance.condition="none"}}}

function shouldBirth(){const w=state.pregnancyWeek;if(w<32)return false;if(w>=42)return true;const base={32:3,33:4,34:6,35:8,36:12,37:18,38:26,39:36,40:50,41:70}[w]||3;return Math.random()*100<base+state.stats.prenatalRisk*.17+state.seed.premature*.06;}
function doBirth(){
  const week=state.pregnancyWeek;state.flags.premature=week<37;let health=state.seed.baselineHealth+state.stats.prenatalCare*.18-state.stats.prenatalRisk*.24+ri(-15,15);if(state.seed.congenital>92)health-=ri(22,44);if(week<34)health-=ri(12,24);else if(week<37)health-=ri(3,10);health=clamp(Math.round(health),8,100);state.stats.health=health;if((week<35&&Math.random()<.72)||health<43)state.flags.nicu=true;if(health<49||(state.seed.congenital>89&&Math.random()<.5))state.flags.chronic=true;if(health<24||(state.seed.congenital>97&&Math.random()<.55))state.flags.severeMedical=true;state.phase="child";state.age=0;state.actionCount=0;if(state.flags.severeMedical){state.appearance.condition="medical";state.appearance.expression="sick"}else if(state.flags.chronic){state.appearance.condition="sick";state.appearance.expression="sick"}else state.appearance.expression="neutral";
  let rec=`${state.childName}が妊娠${week}週で生まれた。`;if(state.flags.nicu)rec+=" 出生後はNICUでの管理が必要になった。";else if(state.flags.chronic)rec+=" 出生後、継続的な通院が必要だと分かった。";else rec+=" 出生直後の状態はおおむね安定していた。";addHistory("0歳・出生",rec,"birth");if(state.flags.premature)discover("早産");if(state.flags.nicu)discover("NICU経験");if(state.flags.chronic)discover("持病");if(state.flags.severeMedical)discover("継続的医療ケア");gameAudio.startBGM(state.flags.severeMedical?"hospital":"home");render();
  const partner=state.playerRole==="mother"?"father":"mother";const lines=[{speaker:partner,expression:state.flags.nicu?"scared":"happy",text:state.flags.nicu?["……小さい。大丈夫かな。","ちゃんと、元気になってくれるよな。"]:["……生まれた。","ちっちゃいな……。"]},{speaker:"player",expression:state.flags.nicu?"sad":"happy",text:state.flags.nicu?["今は先生たちに任せよう。","……うん。"]:["やっと会えたね。","この子が、{name}。"]}];runDialogue(resolveDialogue(lines),showActions);
}

function confirmAgeUp(){gameAudio.click();openModal("AGE UP",`${state.age}歳を終える`,`<p class="desc">${esc(state.childName)}は現在${state.age}歳です。この年齢での行動は${state.actionCount}回。</p><p class="desc">年齢はいつでも上げられます。今の年齢には戻れません。</p><button id="yesAgeUp" class="main-btn">${state.age+1}歳になる</button><button id="noAgeUp" class="sub-btn">まだ${state.age}歳で過ごす</button>`);$("#yesAgeUp").onclick=()=>{closeModal();ageUp()};$("#noAgeUp").onclick=closeModal;}
function ageUp(){state.age++;state.actionCount=0;addHistory(`${state.age}歳`,`${state.childName}は${state.age}歳になった。`,"birthday");gameAudio.confirm();vibrate(24);if(state.age>=22){finishGame();return}runDialogue([{speaker:"child",expression:"happy",text:ageLine(state.age)}],showActions);render();}
function ageLine(age){if(age<=2)return rnd(["おっきくなった？","またひとつ、おっきくなった！"]);if(age<=6)return rnd(["今日からまた、おにいさん／おねえさん？","今年はなにしようかな！"]);if(age<=12)return rnd(["今年もよろしく。","もう子どもじゃないし。……たぶん。"]);if(age<=17)return rnd(["また一歳増えた。","別に、誕生日だからって何も変わんないけど。"]);return rnd(["もう大人って言われる年なんだな。","これからのこと、ちゃんと考えないとな。"]);}
function finishGame(){state.ended=true;state.age=22;addHistory("22歳",`${state.childName}は22歳になった。`,"ending");gameAudio.startBGM("ending");$("#playScreen").classList.add("hidden");$("#endingScreen").classList.remove("hidden");renderEnding();render();}
function renderEnding(){const p=endingProfile();$("#endingTitle").textContent=`${state.childName}、22歳`;$("#endingCards").innerHTML=Object.entries(p).map(([k,v])=>`<div class="ending-card"><span>${esc(k)}</span><b>${esc(v)}</b></div>`).join("");}
function endingProfile(){const s=state.stats;let personality="穏やかな大人";if(s.delinquency>55)personality="荒っぽさを残した大人";else if(s.rebellion>58)personality="反骨心の強い大人";else if(s.kindness>55)personality="人への気遣いが自然にできる大人";else if(s.selfEsteem<-15)personality="自分に自信を持ちにくい大人";let independence="必要なことは自分で決められる";if(s.dependence>65&&s.independence<35)independence="養育者への依存がかなり強い";else if(s.independence>65)independence="かなり自立している";else if(s.independence<20)independence="大人になりきれない部分が残っている";let health=healthText();if(state.flags.nicu&&!state.flags.chronic)health+="（乳児期にNICU経験）";let family=s.attachment>55?"養育者との結びつきが強い":"養育者とは一定の距離がある";if(s.dependence>65)family+="・依存傾向あり";let home="おおむね安定";if(s.cleanliness<30||s.money<25)home="不安定さが残った";else if(s.cleanliness>72&&s.money>70)home="かなり整っている";return{"性格":personality,"自立":independence,"健康":health,"養育者との関係":family,"生活環境":home};}

function applyEffects(e){Object.entries(e).forEach(([k,v])=>{if(k in state.stats)state.stats[k]=clamp(state.stats[k]+v,-100,100)});}
function conditionsPass(cs){return cs.every(c=>{const v=c.source==="flags"?state.flags[c.key]:c.source==="stats"?state.stats[c.key]:state[c.key];if("eq"in c&&v!==c.eq)return false;if("neq"in c&&v===c.neq)return false;if("gte"in c&&!(v>=c.gte))return false;if("lte"in c&&!(v<=c.lte))return false;return true});}
function discover(x){if(x&&!state.discovered.includes(x))state.discovered.push(x)}function addHistory(label,text,eventId){state.history.push({label,text,eventId,ts:Date.now()})}function pickText(v){return Array.isArray(v)?rnd(v):v}function fill(s=""){return String(s).replaceAll("{name}",state.childName).replaceAll("{player}",state.playerRole==="mother"?"母":"父").replaceAll("{partner}",state.playerRole==="mother"?"父":"母")}function esc(s=""){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}function vibrate(ms){if(navigator.vibrate)navigator.vibrate(ms)}
function healthText(){if(state.phase==="pregnancy")return"出生前";if(state.flags.severeMedical)return"常時医療あり";if(state.flags.chronic)return"定期通院";if(state.stats.health>=75)return"良好";if(state.stats.health>=50)return"おおむね安定";return"やや不安定"}function homeText(){const s=state.stats;if(s.cleanliness<25||s.money<20)return"かなり荒れている";if(s.cleanliness<42||s.money<35)return"少し傷んでいる";if(s.cleanliness>72&&s.money>70)return"かなり整っている";if(s.cleanliness>64)return"きれい";return"普通"}function moodText(){const e=state.appearance.expression;return({happy:"ごきげん",sad:"悲しい",angry:"怒っている",scared:"不安",sick:"ぐったり",sleepy:"眠そう",hurt:"痛そう",neutral:"普通"})[e]||"普通"}

function render(){
  $("#ageView").textContent=state.phase==="pregnancy"?`妊娠 ${state.pregnancyWeek}週`:state.age>=0?`${state.age}歳`:"開始前";$("#healthView").textContent=state.started?healthText():"―";$("#homeView").textContent=homeText();$("#moodView").textContent=state.started?moodText():"―";$("#phaseLabel").textContent=state.phase==="pregnancy"?"PREGNANCY":state.ended?"AGE 22":`AGE ${state.age}`;$("#kindnessStat").textContent=Math.round(state.stats.kindness);$("#independenceStat").textContent=Math.round(state.stats.independence);$("#attachmentStat").textContent=Math.round(state.stats.attachment);$("#rebellionStat").textContent=Math.round(state.stats.rebellion);
  const scene=$("#scene");scene.classList.remove("home-normal","home-worn","home-bad","home-good");if(state.stats.cleanliness<25||state.stats.money<20)scene.classList.add("home-bad");else if(state.stats.cleanliness<43||state.stats.money<35)scene.classList.add("home-worn");else if(state.stats.cleanliness>70&&state.stats.money>65)scene.classList.add("home-good");else scene.classList.add("home-normal");$("#mess").classList.toggle("hidden",state.stats.cleanliness>=35);
  $("#fatherSprite").classList.toggle("hidden",!state.started||(state.phase!=="pregnancy"&&state.playerRole==="mother"&&state.flags.partnerGone));$("#motherSprite").classList.toggle("hidden",!state.started||(state.phase!=="pregnancy"&&state.playerRole==="father"&&state.flags.partnerGone));$("#childSprite").classList.toggle("hidden",!state.started||state.phase==="pregnancy");if(state.phase==="pregnancy")$("#sceneLabel").textContent=`妊娠${state.pregnancyWeek}週。まだ子どもの姿はない。`;else if(state.started)$("#sceneLabel").textContent=`${state.childName}、${state.age}歳。`;
  const child=$("#childSprite");[...child.classList].filter(x=>x.startsWith("stage-")||x.startsWith("expression-")||x.startsWith("injury-")||x==="medical-needs").forEach(x=>child.classList.remove(x));if(state.age===0)child.classList.add("stage-baby");else if(state.age<=3)child.classList.add("stage-toddler");else if(state.age<=11)child.classList.add("stage-kid");else if(state.age<=17)child.classList.add("stage-teen");else child.classList.add("stage-adult");child.classList.add("expression-"+(state.appearance.expression||"neutral"));if(state.appearance.injury&&state.appearance.injury!=="none")child.classList.add("injury-"+state.appearance.injury);if(state.flags.severeMedical||state.appearance.condition==="medical")child.classList.add("medical-needs");
}

function showRecords(){const s=state.stats;openModal("RECORD","成長記録",`<div class="stat-grid">${stat("名前",state.childName)}${stat("現在",state.phase==="pregnancy"?`妊娠${state.pregnancyWeek}週`:`${state.age}歳`)}${stat("健康",healthText())}${stat("優しさ",Math.round(s.kindness))}${stat("自立",Math.round(s.independence))}${stat("親子関係",Math.round(s.attachment))}${stat("依存",Math.round(s.dependence))}${stat("反抗",Math.round(s.rebellion))}${stat("家の状態",homeText())}</div><h3>発見済み</h3><div class="record"><p>${state.discovered.length?state.discovered.map(esc).join(" ／ "):"まだありません。"}</p></div><h3>全記録</h3><div class="record-list">${state.history.length?state.history.map(h=>`<div class="record"><small>${esc(h.label)}</small><p>${esc(h.text)}</p></div>`).join(""):"<p>まだありません。</p>"}</div>`);}
function showSaves(){let html='<div class="save-grid">';for(let i=1;i<=3;i++){const s=getSave(i),desc=s?`${s.childName}／${s.phase==="pregnancy"?`妊娠${s.pregnancyWeek}週`:`${s.age}歳`}`:"空き";html+=`<div class="slot"><h3>SLOT ${i}</h3><p>${esc(desc)}</p><button class="sub-btn" data-save="${i}">セーブ</button><button class="ui-btn" data-load="${i}" ${s?"":"disabled"}>ロード</button><button class="ui-btn" data-del="${i}" ${s?"":"disabled"}>削除</button></div>`}html+="</div>";openModal("SAVE","セーブ／ロード",html);$$('[data-save]').forEach(b=>b.onclick=()=>{localStorage.setItem("life22_save_"+b.dataset.save,JSON.stringify(state));gameAudio.confirm();showSaves()});$$('[data-load]').forEach(b=>b.onclick=()=>{const s=getSave(b.dataset.load);if(!s)return;const base=BASE();state=Object.assign(base,s);state.stats=Object.assign(base.stats,s.stats||{});state.flags=Object.assign(base.flags,s.flags||{});state.appearance=Object.assign(base.appearance,s.appearance||{});state.settings=Object.assign(base.settings,s.settings||{});applySettings();$("#setupScreen").classList.add("hidden");$("#endingScreen").classList.toggle("hidden",!state.ended);$("#playScreen").classList.toggle("hidden",state.ended);closeModal();render();if(state.ended)renderEnding();else showActions()});$$('[data-del]').forEach(b=>b.onclick=()=>{localStorage.removeItem("life22_save_"+b.dataset.del);showSaves()});}
function getSave(i){try{const r=localStorage.getItem("life22_save_"+i);return r?JSON.parse(r):null}catch{return null}}
function showSettings(){openModal("SETTINGS","音と読み上げ",`${toggleRow("BGM","bgm",state.settings.bgm)}${toggleRow("効果音・ボタン音","se",state.settings.se)}${toggleRow("セリフ読み上げ","voice",state.settings.voice)}<p class="desc">BGMと効果音は外部素材なしでも鳴る簡易音源です。あとで assets/audio にMP3等を入れて差し替えられます。読み上げ音声は端末・ブラウザ側の日本語音声を使用します。</p>`);$$('[data-setting]').forEach(b=>b.onclick=()=>{const k=b.dataset.setting;state.settings[k]=!state.settings[k];applySettings();showSettings()});}
function toggleRow(label,key,on){return`<div class="toggle-row"><div><b>${esc(label)}</b></div><button class="switch ${on?"on":""}" data-setting="${key}"></button></div>`}function applySettings(){gameAudio.setBGM(state.settings.bgm);gameAudio.setSE(state.settings.se);gameAudio.setVoice(state.settings.voice)}
function showDiary(){const p=endingProfile();let out=[];out.push(`<p>${esc(fill(rnd(diary.intro)))}</p>`);const birth=state.history.find(h=>h.eventId==="birth");if(birth)out.push(`<h3>0歳・出生</h3><p>${esc(birth.text)}</p>`);const ages={};state.history.forEach(h=>{const m=h.label.match(/^(\d+)歳/);if(m)(ages[m[1]]??=[]).push(h.text)});Object.keys(ages).map(Number).sort((a,b)=>a-b).forEach(a=>{const arr=ages[a].filter((v,i,x)=>x.indexOf(v)===i).slice(0,6);out.push(`<h3>${a}歳</h3><p>${esc(diaryPrefix(a))} ${esc(arr.join(" "))}</p>`)});const close=fill(rnd(diary.closing)).replaceAll("{personality}",p["性格"]).replaceAll("{independence}",p["自立"]);out.push(`<h3>22歳・現在</h3><p>${esc(close)}</p>`);openModal("DIARY",`${state.childName}の22年日記`,`<div class="diary">${out.join("")}</div>`)}
function diaryPrefix(a){if(a<=2)return rnd(diary.early);if(a<=6)return rnd(diary.childhood);if(a<=12)return rnd(diary.school);if(a<=17)return rnd(diary.teen);return rnd(diary.adult)}
function openModal(k,t,b){$("#modalKicker").textContent=k;$("#modalTitle").textContent=t;$("#modalBody").innerHTML=b;$("#modalBackdrop").classList.remove("hidden")}function closeModal(){$("#modalBackdrop").classList.add("hidden")}function stat(k,v){return`<div class="stat"><span>${esc(k)}</span><b>${esc(String(v))}</b></div>`}
window.addEventListener("DOMContentLoaded",async()=>{init();try{await loadData()}catch(e){console.error(e);alert("JSONの読み込みに失敗しました。GitHub Pages上で開いてください。")} });
